INSERT INTO "public"."Checkpoints" ("id", "State", "County", "City", "Location", "Description", "Date", "Time", "Source", "created_at", "mapurl", "location_id") VALUES ('1', 'CA', 'Imperial', 'El Centro', 'Imperial Avenue and Holt Avenue', 'El Centro Police will run a DUI checkpoint to remove impaired drivers and improve safety.', '2025-12-21', '6pm - 2am PST', 'https://www.facebook.com/ElCentroPoliceDepartment/posts/on-december-21-2025-the-el-centro-police-department-will-conduct-a-driving-under/1152055027079138/', '2025-12-03 06:45:31.826547+00', 'https://www.google.com/maps/place/W+Holt+Ave+%26+Imperial+Ave,+El+Centro,+CA+92243/@32.787613,-115.5701203,228m/data=!3m1!1e3!4m6!3m5!1s0x80d760d2e1d3c995:0x69a2dd5a7ee85ecd!8m2!3d32.7876799!4d-115.5697414!16s%2Fg%2F11gf4q42lp!5m1!1e4?entry=ttu&g_ep=EgoyMDI2MDEyMS4wIKXMDSoASAFQAw%3D%3D', '6e3d4cfa-1dd3-406f-8fe2-ab110794cecd'), ('2', 'CA', 'Los Angeles', 'Glendora', 'undisclosed location', 'PRESS RELEASE - Glendora, CA

On December 5th, the Glendora Police Department will conduct a driving under the influence (DUI) Checkpoint from 6:30 p.m. to 1:30 a.m. at an undisclosed location.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Police Chief Mike Randazzo said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

Read the full press release by clicking the link in the bio or swiping over on the photo', '2025-12-05', '6:30pm - 1:30am PST', 'https://www.instagram.com/p/DRwHXivkQBS/', '2025-12-04 08:26:46.848135+00', 'https://www.google.com/maps/search/los+angeles+California+Glendora+Grand+Ave+%26+Foothill+Blvd+near+Sprouts+Marshalls/@34.1274732,-117.874071,429m/data=!3m1!1e3?entry=ttu&g_ep=EgoyMDI2MDEyNS4wIKXMDSoASAFQAw%3D%3D', '83ef1bb7-bd15-43d9-bb73-be4eada79c7c'), ('3', 'CA', 'Los Angeles', 'Monterey Park', 'undisclosed location', 'Union City Police Department Holding DUI/DL Checkpoint December 20, 2025.
Press Release also attached
Union City, Calif. – On 12/20/25, the Union City Police Department will conduct a driving under the influence (DUI/DL) Checkpoint at an undisclosed location. 
DUI/DL checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI/DL checkpoints are to promote public safety by taking suspected impaired drivers off the road.
“Impaired drivers put others on the road at significant risk,” Sgt. Steven Fong said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”
The Union City Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.
For Traffic or specific grant-related questions, please contact: 
Traffic Sergeant Steven Fong
510-471-1365 (Main Line)
510-675-5221(Direct Line)
Stevenf@unioncity.org (Email)', '2025-12-05', '6pm-2am PST', 'https://www.facebook.com/unioncitypd/posts/union-city-police-department-holding-duidl-checkpoint-december-20-2025press-rele/1267994332020044/', '2025-12-04 08:42:06+00', 'https://www.google.com/maps/place/S+Atlantic+Blvd+%26+W+Riggin+St,+Monterey+Park,+CA+91754,+USA/@34.0374555,-118.1472495,361m/data=!3m1!1e3!4m6!3m5!1s0x80c2cf90910380d3:0x3de54fcfc9accd39!8m2!3d34.0375007!4d-118.1463541!16s%2Fg%2F11f32gzgfx?entry=ttu&g_ep=EgoyMDI2MDEyNS4wIKXMDSoASAFQAw%3D%3D', '4cb96c6d-fb51-4a01-affb-cf263330254c'), ('4', 'CA', 'Alameda ', 'Pleasanton ', 'on Santa Rita Road between Rosewood Drive and Pimlinco Drive', 'DUI Checkpoint Planned for December 5
The Pleasanton Police Department will conduct a DUI checkpoint on Friday, December 5, on Santa Rita Road between Rosewood Drive and Pimlico Drive. The checkpoint will run from 6:00 p.m. to midnight.
DUI checkpoints help reduce impaired-driving crashes by raising awareness and removing impaired drivers from the road. During Friday’s operation, officers will be looking for signs of alcohol or drug impairment, including impairment caused by certain prescription medications or marijuana — especially when combined with other substances. Specially trained officers will be on scene to evaluate drivers suspected of being under the influence of drugs.
Driving under the influence has serious consequences: jail time, fines, DUI classes, license suspension, and other costs that can exceed $10,000.
Please plan ahead. Designate a sober driver or arrange another safe way home.
If you see a driver who appears impaired, call 911 immediately.
This checkpoint is funded by the California Highway Patrol Cannabis Tax Fund Grant Program.', '2025-12-05', '6pm-12am PST', 'https://www.facebook.com/PleasantonPoliceCA/posts/-dui-checkpoint-planned-for-december-5the-pleasanton-police-department-will-cond/1309730961183928/', '2025-12-04 08:47:10+00', null, 'ef7edfd2-e752-49da-b069-65f799618440'), ('5', 'CA', 'Alameda ', ' Union City', ' undisclosed location', 'Union City Police Department Holding DUI/DL Checkpoint December 20, 2025.
Press Release also attached
Union City, Calif. – On 12/20/25, the Union City Police Department will conduct a driving under the influence (DUI/DL) Checkpoint at an undisclosed location. 
DUI/DL checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI/DL checkpoints are to promote public safety by taking suspected impaired drivers off the road.
“Impaired drivers put others on the road at significant risk,” Sgt. Steven Fong said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”
The Union City Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.
For Traffic or specific grant-related questions, please contact: 
Traffic Sergeant Steven Fong
510-471-1365 (Main Line)
510-675-5221(Direct Line)
Stevenf@unioncity.org (Email)', '2025-12-20', 'undisclosed time PST', 'https://www.facebook.com/unioncitypd/posts/union-city-police-department-holding-duidl-checkpoint-december-20-2025press-rele/1267994332020044/', '2025-12-04 08:50:21+00', null, '5957c6ca-beae-412c-8fe1-dea750d2898d'), ('6', 'CA', 'Solono', 'Vacaville', 'undisclosed location', 'According to Vacaville police, the checkpoint will start at 5 p.m. and will last until midnight. The checkpoints are determined based on data of crashes that were caused due to being impaired while driving.

“Impaired drivers put others on the road at significant risk,” Lieutenant Rob Myers, VVPD Traffic Unit Commander, said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

VPD said that officers want to remind the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving.', '2025-12-19', '5pm-midnight PST', 'https://fox40.com/news/local-news/vacaville-california/vacaville-police-schedule-dui-checkpoint-targeting-impaired-drivers-heres-when/', '2025-12-04 08:56:16+00', null, '41ed5612-482d-403d-af24-c2100b401da7'), ('7', 'CA', 'Monterey', 'Greenfield ', 'undisclosed location', 'Greenfield Police Department Holding DUI/DL Checkpoint December 19, 2025
On 12/19/2025, the Greenfield Police Department will conduct a driving under the influence (DUI) and Driver’s License (DL) Checkpoint from 6PM to 10PM at an undisclosed location within the city limits.
DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.
Greenfield Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Highway Patrol through the Cannabis Tax Fund Grant Program.
********
El 19 de Diciembre del 2025, el Departamento de Policía de Greenfield llevará a cabo un puesto de control para conductores bajo los efectos del alcohol (DUI) y de licencias de conducir (DL) de 6:00 p. m. a 10:00 p. m. en un lugar no revelado dentro de los límites de la ciudad.
Las ubicaciones de los puestos de control para conductores bajo los efectos del alcohol se determinan basados de datos que muestran incidentes de accidentes relacionados con la conducción en estado de ebriedad. El objetivo principal de los puestos de control para conductores bajo los efectos del alcohol es promover la seguridad pública removiendo de la carretera a los conductores sospechosos de conducir en estado de ebriedad.
El Departamento de Policía de Greenfield recuerda al público que la conducción en estado de ebriedad no se produce solo por el alcohol. Algunos medicamentos recetados y de venta libre pueden interferir con la conducción. Si bien la marihuana medicinal y recreativa es legal, conducir bajo los efectos de la marihuana es ilegal. Los conductores acusados ​​de conducir bajo los efectos del alcohol por primera vez enfrentan un promedio de $13,500 en multas y sanciones, así como la suspensión de la licencia.
 Los fondos de este programa fueron proporcionados por una subvención de la Patrulla de Caminos de California, a través del Programa de Subvenciones del Fondo Fiscal de Cannabis.Greenfield Police Department Holding DUI/DL Checkpoint December 19, 2025
On 12/19/2025, the Greenfield Police Department will conduct a driving under the influence (DUI) and Driver’s License (DL) Checkpoint from 6PM to 10PM at an undisclosed location within the city limits.
DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.
Greenfield Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Highway Patrol through the Cannabis Tax Fund Grant Program.
********
El 19 de Diciembre del 2025, el Departamento de Policía de Greenfield llevará a cabo un puesto de control para conductores bajo los efectos del alcohol (DUI) y de licencias de conducir (DL) de 6:00 p. m. a 10:00 p. m. en un lugar no revelado dentro de los límites de la ciudad.
Las ubicaciones de los puestos de control para conductores bajo los efectos del alcohol se determinan basados de datos que muestran incidentes de accidentes relacionados con la conducción en estado de ebriedad. El objetivo principal de los puestos de control para conductores bajo los efectos del alcohol es promover la seguridad pública removiendo de la carretera a los conductores sospechosos de conducir en estado de ebriedad.
El Departamento de Policía de Greenfield recuerda al público que la conducción en estado de ebriedad no se produce solo por el alcohol. Algunos medicamentos recetados y de venta libre pueden interferir con la conducción. Si bien la marihuana medicinal y recreativa es legal, conducir bajo los efectos de la marihuana es ilegal. Los conductores acusados ​​de conducir bajo los efectos del alcohol por primera vez enfrentan un promedio de $13,500 en multas y sanciones, así como la suspensión de la licencia.
 Los fondos de este programa fueron proporcionados por una subvención de la Patrulla de Caminos de California, a través del Programa de Subvenciones del Fondo Fiscal de Cannabis.', '2025-12-19', '6pm-10pm PST', 'https://www.facebook.com/greenfieldcapolice/posts/greenfield-police-department-holding-duidl-checkpoint-december-19-2025on-1219202/1175283224788874/', '2025-12-04 09:03:06+00', null, '0da73210-1d38-41d4-a974-3a5b575a6bf1'), ('8', 'CA', 'San diego', 'Oceanside ', 'undisclosed location', ' A Driver’s License/Driving Under the Influence (DUI) Checkpoint will be facilitated by the Oceanside Police Department at an undisclosed location in the City of Oceanside on Friday, December 12th, from 6 p.m. to 2 a.m. on Saturday, December 13th.

DUI checkpoint locations are determined based on data showing incidents of impaired-driving crashes. The primary purpose of DUI checkpoints is to promote public safety by removing drivers suspected of DUI from the roadway while also educating non-impaired motorists about the dangers of driving under the influence of alcohol and/or drugs. Officers will also ensure motorists passing through the checkpoint are properly licensed.

Although DUI incidents are commonly associated with alcohol, many prescription medications can also impair a driver. While a limited amount of cannabis (marijuana) is legal for adults 21 years and older to possess, it remains unlawful to drive while under the influence of cannabis. Motorists driving under the influence of any combination of drugs and/or alcohol are subject to arrest.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-12', '6pm-2am PST', 'https://www.oceansidepolice.com/Home/Components/News/News/841/12646 ', '2025-12-04 09:05:59+00', null, '70fe7f4a-c0d3-4605-a744-150b31c3bdb1'), ('9', 'CA', 'Riverside', 'San Jacinto', 'undisclosed location.', 'San Jacinto, Calif. – On Friday, December 5th, 2025, the Riverside County Sheriff’s Office – San Jacinto Station will conduct a driving under the influence (DUI) Checkpoint from 8 p.m. to 2 a.m. at an undisclosed location.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Sergeant Patrick Lynch said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The San Jacinto Sheriff Station reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-05', '8am-2am PST', 'https://www.riversidesheriff.org/m/newsflash/Home/Detail/6796', '2025-12-04 09:06:41+00', null, 'a6e1925a-f4c5-4d8a-9a1b-0db685f2293c'), ('10', 'CA', 'Fresno', null, 'undisclosed location.', 'FRESNO, Calif. (KSEE/KGPE) – Eleven drivers were arrested on suspicion of driving under the influence during a saturation operation Saturday, according to the Fresno Police Department.

Police say a first-time DUI driver could face an average of $13,500 in fines and penalties, as well as a suspended license.

They also say a series of DUI enforcement patrols and checkpoints will be held throughout the year, including a DUI enforcement operation on December 20.

Funding for the program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-20', 'not specified ', 'https://www.yourcentralvalley.com/news/local-news/dui-enforcement-fresno-police/', '2025-12-04 09:09:50+00', null, 'e12c76cd-a54c-489f-9176-3b2f269a879c'), ('11', 'CA', 'Placer', 'Lincoln', 'undisclosed location.', 'Authorities said that officers want to remind the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving.

Lincoln police said in a press release, “Always follow directions for use and read warning labels about driving or operating heavy machinery, which includes driving a car.”

“If you plan on drinking or taking medications that may impact your ability to drive safely, plan on staying at home,” LPD said.

Officials stated that while medicinal and recreational marijuana is legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license, LPD said. Funding for this program was provided by a grant from the California Highway Patrol Cannabis Tax Fund.

LPD said its officers are committed to keeping drivers and the public safe on the roadways in and around the city.', '2025-12-06', '7pm-midnight PST', 'https://fox40.com/news/dui-checkpoint-targeting-impaired-drivers-scheduled-within-the-city-lincoln-police-say/', '2025-12-04 09:16:43+00', null, '67bb963f-9fbc-4cbb-9b34-fd3e5d765d7f'), ('12', 'CA', 'Imperial ', 'El Centro', 'Imperial Avenue and Holt Avenue', 'El Centro, California. – On Friday, December 19th, 2025 the El Centro Police Department will conduct a driving under the influence (DUI) Checkpoint from 6 p.m. (12/19/25) to 2 a.m. (12/20/25) near the intersection of Imperial Avenue and Holt, in the City of El Centro.    

 DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.

 “Impaired drivers put others on the road at significant risk,” Sergeant Adrian Chilpa, said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improves traffic safety.”

 El Centro Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

 Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

 Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-19', '6pm - 2am PST', 'https://www.cityofelcentro.org/m/newsflash/Home/Detail/73', '2025-12-09 08:58:15+00', 'https://www.google.com/maps/place/W+Holt+Ave+%26+Imperial+Ave,+El+Centro,+CA+92243/@32.787613,-115.5701203,228m/data=!3m1!1e3!4m6!3m5!1s0x80d760d2e1d3c995:0x69a2dd5a7ee85ecd!8m2!3d32.7876799!4d-115.5697414!16s%2Fg%2F11gf4q42lp!5m1!1e4?entry=ttu&g_ep=EgoyMDI2MDEyMS4wIKXMDSoASAFQAw%3D%3D', 'fb39f11a-1e50-4dac-9ff3-44a61e59bb3a'), ('13', 'CA', 'Los Angeles', 'Newark', 'City of Newark.', 'Newark Police Department Holding DUI/License Checkpoint December 12, 2025
Newark, Calif. – On December 12, 2025, the Newark Police Department will conduct a Driving Under the Influence (DUI) and License Checkpoint from 6 pm to 2 am in the City of Newark.
DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI/License checkpoints is to promote public safety by taking suspected impaired drivers off the road.
“Impaired drivers put others on the road at significant risk,” Traffic Sergeant Fredstrom said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improves traffic safety.”
The Newark Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-12', '6pm-2am PST', 'https://www.facebook.com/NewarkPolice/posts/newark-police-department-holding-duilicense-checkpoint-december-12-2025-newark-c/1142089224754586/', '2025-12-09 09:00:24+00', null, '457c63a0-9194-4fd5-a6b0-c88a5f99896e'), ('14', 'CA', 'Los Angeles', 'Jurupa Valley ', 'undisclosed location', 'Jurupa Valley, Calif. – On Friday, December 12, 2025, The Riverside County Sheriff’s Office, Jurupa Valley Station will conduct a driving under the influence (DUI) Checkpoint from 8:00 p.m. to 2:00 a.m. at an undisclosed location.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Sergeant Rafael Lopez said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improves traffic safety.”

The Jurupa Valley Station reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-12', '8pm-2am PST', 'https://www.riversidesheriff.org/m/newsflash/Home/Detail/6808', '2025-12-09 09:02:25.67794+00', null, '0c6736cd-26c4-43d0-b498-2a38e2f60ccf'), ('15', 'CA', 'Los Angeles', 'Fairfield', 'North Texas Street and Marigold Street. ', 'Fairfield Police Department Holding DUI/License Checkpoint on Friday, December 12
Fairfield, Calif. – On Friday, December 12, the Fairfield Police Department will conduct a driving under the influence (DUI) Checkpoint from 6 p.m. to 12 a.m. at a North Texas Street and Marigold Street. 
DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.
“Impaired drivers put others on the road at significant risk,” Sergeant Josh Bender said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”
The Fairfield Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.
Edit: The question of why we advertise checkpoints in advance is a recurring one  We have responded to multiple individual comments and pinned this information, but please be advised that advace notice is required by law.', '2025-12-12', '6pm-12am PST', 'https://www.facebook.com/FairfieldPolice/posts/fairfield-police-department-holding-duilicense-checkpoint-on-friday-december-12-/1242555404587015/', '2025-12-09 09:05:30+00', null, '490da12c-4d7e-4aa2-ba7c-5aa576961e7e'), ('16', 'CA', 'Los Angeles', 'Menifee', 'undisclosed location', 'The Menifee Police Department will hold a DUI/Driver’s License Checkpoint Saturday, December 13, 2025, from 7:00 pm to 2:00 am at an undisclosed location within the Menifee city limits.

Checkpoint locations are chosen based on the history of DUI crashes and arrests in the city. The primary purpose of checkpoints is not to make arrests, but to promote public safety by deterring drivers from driving impaired.

During the checkpoint, officers will look for signs that drivers are under the influence of alcohol and/or drugs.

The Menifee Police Department is committed to keeping our community safe and free of DUI drivers. Not only do we conduct checkpoints, but we also send out individual police units throughout the year to look for these dangerous drivers.', '2025-12-13', '7pm-2am PST', 'https://www.instagram.com/p/DR3IiPdDWlV/', '2025-12-09 09:07:22+00', null, '28c777ab-2aeb-4f52-9060-f1d69edbf22e'), ('17', 'CA', 'Los Angeles', 'Worcester', 'undisclosed location', 'Worcester, MA – Drivers in Worcester County should expect an overnight sobriety checkpoint later next week as the Massachusetts State Police prepare to conduct an OUI enforcement operation beginning Thursday night.

According to the Massachusetts State Police, the checkpoint will run from Thursday, December 11, into Friday, December 12, 2025, and is part of an ongoing statewide initiative aimed at reducing impaired driving. The agency said the goal is to educate motorists while identifying drivers who may be operating under the influence of alcohol or drugs.', '2025-12-11', 'N/A', 'https://countryherald.com/news/massachusetts-dui-checkpoint-state-police-target-worcester-county-starting-dec-11/', '2025-12-09 09:07:45+00', null, '43a52451-fb06-48b7-8eb8-4a08ef8e1a0e'), ('18', 'CA', 'Los Angeles', 'Signal Hill', 'undisclosed location', 'The Signal Hill Police Department will be conducting a DUI and Driver’s License Checkpoint on Friday, December 12, 2025. 

The primary purpose of a DUI Checkpoint is to promote public safety by taking suspected impaired drivers off the road. Officers will be looking for signs of alcohol and/or drug impairment, while also checking drivers for proper licensing. 

Funding for this DUI Checkpoint was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-12', 'N/A', 'https://www.instagram.com/p/DR45oYwCd9o/', '2025-12-09 09:13:48+00', null, 'ccf2c467-bde2-4ae4-a196-56ac4ea594cb'), ('19', 'CA', 'Alameda ', 'Hayward ', 'undisclosed location', 'Press release - DUI Checkpoint scheduled for December 20, 2025 ', '2025-12-20', '6pm-2am PST', 'https://www.facebook.com/HaywardPoliceDept/posts/press-release-dui-checkpoint-scheduled-for-december-20-2025/872542625286092/', '2025-12-09 09:15:39+00', null, '9c0404a4-fd1a-4fb6-9e0c-3b81c56ab912'), ('20', 'CA', 'Kern', 'Kern', '5th St. and Cooper Ave', 'Lauderdale County sheriff’s deputies will be looking for impaired drivers heading into the holidays after the Sheriff’s Department announced a series of sobriety checkpoints will be set up throughout the county over the next few weeks.     The department is required to announce checkpoints ahead of time if the main goal will be to check for impaired drivers. Safety checkpoints, where deputies check for seat belts, insurance and drivers’ licenses, do not have to be publicized in advance.', '2025-12-13', '7:30 PM PST', 'https://meridianstar.com/2025/12/03/sheriffs-department-announces-december-sobriety-checkpoints/', '2025-12-09 09:17:59+00', null, '432de8da-ce75-42e0-9533-6aedece23281'), ('21', 'CA', 'Kern', 'Kern', 'Dale Dr. and Marion Dr.', 'Lauderdale County sheriff’s deputies will be looking for impaired drivers heading into the holidays after the Sheriff’s Department announced a series of sobriety checkpoints will be set up throughout the county over the next few weeks.     The department is required to announce checkpoints ahead of time if the main goal will be to check for impaired drivers. Safety checkpoints, where deputies check for seat belts, insurance and drivers’ licenses, do not have to be publicized in advance.', '2025-12-14', '8:30 PM PST', 'https://meridianstar.com/2025/12/03/sheriffs-department-announces-december-sobriety-checkpoints/', '2025-12-09 09:20:32+00', null, 'fc8f2633-c41d-4f7b-b893-25d7d4d822c5'), ('22', 'CA', 'Kern', 'Kern', 'Highway 11/80 and Butts Rd.', 'Lauderdale County sheriff’s deputies will be looking for impaired drivers heading into the holidays after the Sheriff’s Department announced a series of sobriety checkpoints will be set up throughout the county over the next few weeks.     The department is required to announce checkpoints ahead of time if the main goal will be to check for impaired drivers. Safety checkpoints, where deputies check for seat belts, insurance and drivers’ licenses, do not have to be publicized in advance.
', '2025-12-15', '9:30 PM PST', 'https://meridianstar.com/2025/12/03/sheriffs-department-announces-december-sobriety-checkpoints/', '2025-12-09 09:24:07+00', null, '4a1d5f1f-c67b-42f4-bc73-686a056de470'), ('23', 'CA', 'Santa Cruz', 'Santa Cruz ', 'Ocean St corridor.', '*Santa Cruz Police to Conduct DUI Checkpoint*
On Friday, December 12th, 2025, from 10pm to 2am, the Santa Cruz Police Department will be conducting a “Driving Under the Influence” (DUI) sobriety checkpoint on the Ocean St corridor.  Funding for this checkpoint is provided to the Santa Cruz Police Department by a state grant furnished by the California Office of Traffic Safety.
Officers will be contacting drivers passing through the checkpoint for signs of alcohol and/or drug impairment and will strive to only delay motorists momentarily.  Drivers caught driving impaired can expect possible arrest, license suspension, and insurance increases, as well as fines, fees, DUI classes, and other expenses that can exceed $10,000.
The primary purpose of a DUI Checkpoint is to increase awareness, deter impaired driving and to arrest those drivers who are found to be under the influence.  The checkpoint is being held to continue the Santa Cruz Police Department’s commitment to public safety in our community and to remove impaired drivers from our roadways.
The Santa Cruz Police Department urges the community to report DUI drivers by calling 911.', '2025-12-12', '10pm- 2am PST', 'https://www.facebook.com/santacruzpolice/posts/santa-cruz-police-to-conduct-dui-checkpointon-friday-december-12th-2025-from-10p/1287459643410776/', '2025-12-09 09:27:17+00', null, 'cc4a09f0-04ad-45f6-b562-5fa95339dd23'), ('24', 'CA', 'Los Angeles', 'South Pasadena', 'Undisclosed location', 'South Pasadena, Calif. – On December 27, 2025, the South Pasadena Police Department will conduct a driving under the influence (DUI) Checkpoint from 7:00 p.m. to 2:00 a.m. at an undisclosed location within the city.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road..

“Impaired drivers put others on the road at significant risk,” Acting Police Chief Shannon Robledo said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The South Pasadena Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.', '2025-12-27', '7pm-2am PST', 'https://www.southpasadenaca.gov/News-articles/12.17.2025-South-Pasadena-Police-Department-to-Hold-DUI-Checkpoint-December-27?utm_source=chatgpt.com', '2025-12-23 03:46:32.717286+00', null, '610a6a56-53ee-4a33-bee8-6fcc6a9463e7'), ('25', 'CA', 'San Francisco', 'San Francisco', 'undisclosed location', 'The San Francisco Police Department’s Traffic Unit will be conducting a DUI checkpoint patrol Saturday, December 27th, 2025, between the hours of 7:00 P.M. and 3:00 A.M. This checkpoint is a part of the National Highway Traffic Safety Administration’s (NHTSA) national Winter campaign, “Drive Sober or Get Pulled Over”. The holiday season can be dangerous for people on the road. The goal of the campaign is to stop suspected impaired drivers who put others at risk. Research shows that crashes involving an impaired driver can be reduced by up to 20 percent when well-publicized DUI checkpoints and proactive DUI patrols are conducted routinely.

Officers will be looking for signs of alcohol and/or drug impairment. When possible, specially trained officers will be available to evaluate those suspected of drug-impaired driving.  Recent statistics reveal that 30 percent of drivers in fatal crashes had one or more drugs in their systems.  A study of active drivers showed more tested positive for drugs that may impair driving (14 percent) than did for alcohol (7.3 percent). Of the drugs, marijuana was most prevalent, at 7.4 percent, slightly more than alcohol.

Drivers who are caught driving impaired can expect the impact of a DUI arrest to include jail time, fines, fees, DUI classes, and other expenses that can exceed $10,000, not to mention the embarrassment when friends and family find out.

SFPD encourages everyone to celebrate the holiday season responsibly and make this a safe holiday season for everyone on the road. Funding for this saturation is provided to the San Francisco Police Department by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration, reminding everyone to ‘Report Drunk Drivers – Call 9-1-1.', '2025-12-27', '7pm - 3am PST', 'https://www.sanfranciscopolice.org/news/sfpd-conduct-dui-checkpoint-december-27th-2025-25-157?fbclid=IwY2xjawO1zqhleHRuA2FlbQIxMABicmlkETEzS0o2OFVjVXBKaWxrdU1ac3J0YwZhcHBfaWQQMjIyMDM5MTc4ODIwMDg5MgABHqpM9VLxsTndAsM_Ty_tQdjiejztHWiv_1miScfmdP2cY8iSX_BoAnWEMDYa_aem_byhDKctZLHZUryw9XUsmig', '2025-12-23 03:48:29+00', null, '252d8103-0ce8-4fac-8e6e-a2b29c7d77b5'), ('26', 'CA', 'Marin', 'San Rafael', 'undisclosed location', 'San Rafael, CA. – On Friday, January 30th, 2026, the San Rafael Police Department will conduct a driving under the influence (DUI) Checkpoint on January 30th, 2026, from 5:00 pm to 1:00 am at an undisclosed location in the southern area of San Rafael.

DUI checkpoint locations are determined based on data showing the locations of impaired-driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Sergeant Mathis said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The San Rafael Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-30', '5pm - 1am PST', 'https://www.srpd.org/press-release.php?id=835&utm_source=chatgpt.com', '2025-12-23 03:57:34+00', null, '84e1b898-cfa2-467c-8ec9-7d5c978dcab7'), ('27', 'CA', 'Los Angeles', 'San Marino', 'Undisclosed location', null, '2025-12-27', '8pm-2am PST', 'https://sanmarinoca.gov/news_detail_T34_R679.php?utm_source', '2025-12-25 04:31:23+00', null, '81c8c5d5-54bb-4918-9e91-a91a49028bd3'), ('28', 'CA', 'Contra Costa', 'Pinole', 'Undisclosed location', 'The Pinole Police Department Traffic Unit will set up a DUI and driver’s license checkpoint on Saturday, Dec. 27 at 1333 San Pablo Ave. The checkpoint will run from 8:30 p.m. to 2:30 a.m. to help keep roads safe during the holiday weekend. 

Officers will briefly stop drivers to check for signs of alcohol or drug impairment and to make sure drivers have a valid license. Motorists should expect only short delays. Trained officers will also be on hand to evaluate drivers suspected of being impaired by drugs, which are an increasing factor in crashes.

The department says checkpoints like this help deter impaired driving and reduce crashes. From Jan. 1, 2023, through Nov. 30, 2025, Pinole police responded to 382 traffic collisions, including 70 with injuries and one fatal crash. Of those, 44 crashes involved impaired drivers, and officers made 59 DUI arrests during the same period. ', '2025-12-27', '8:30pm-2:20am PST', 'https://richmondstandard.com/richmond/2025/12/22/pinole-police-to-hold-dui-checkpoint-on-dec-27/', '2025-12-25 04:37:10+00', null, 'de178bd8-ab94-4d13-ad3f-a6a38f67ab40'), ('29', 'CA', 'Fresno', null, 'undisclosed location.', 'On December 20, 2025, 14 people were arrested for DUI at a DUI checkpoint. The DUI checkpoint was he…', '2025-12-27', 'not specified', 'https://www.facebook.com/watch/?v=626692760504897', '2025-12-25 04:39:37+00', null, 'e12c76cd-a54c-489f-9176-3b2f269a879c'), ('30', 'CA', 'Contra Costa', 'Martinez-area', ' within Contra Costa County', 'SOBRIETY AND DRIVER LICENSE CHECKPOINT

MARTINEZ, CA – The California Highway Patrol (CHP), Contra Costa Area will be conducting a sobriety and driver license checkpoint on December 26, 2025, within Contra Costa County.

The goal of the CHP is to ensure the safe passage of each and every motorist by targeting roads where there is high frequency of intoxicated or unlicensed drivers. A sobriety and driver license checkpoint is a proven effective tool for achieving this goal and is designed to augment existing patrol operations.

Funding for this sobriety checkpoint was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.
', '2025-12-26', 'undisclosed time', 'https://www.facebook.com/photo/?fbid=1284236230398715&set=a.300612565427758', '2026-01-01 05:05:16.01503+00', null, '52d65f83-2feb-4b8b-afb5-47cd38fcf41b'), ('31', 'CA', 'Kern', 'Desert Hot Spring', 'undisclosed location', '
The Desert Hot Springs Police Department will conduct a DUI Checkpoint on December 26, 2025, at an undisclosed location within the city.

Driving under the influence of alcohol or drugs puts lives at risk and carries serious consequences, including:

• Driver’s license suspension
• Fines and court fees
• Vehicle Towed
• Possible jail time

Plan ahead — designate a sober driver, use a rideshare, or call a friend. Making the right choice can save lives.

Our goal is public safety, not citations. Help us keep our community safe for everyone.', '2025-12-26', 'undisclosed time', 'https://www.facebook.com/photo?fbid=1316930207145265&set=a.302453935259569', '2026-01-01 05:09:05.044275+00', null, '2e5b82ba-0de6-40f7-a988-0aa5713c7a64'), ('32', 'CA', 'San diego', 'Atherton', 'El Camino Real, Middlefield Road and Alameda de Las Pulgas. ', 'OCEANSIDE, CA — A Driver’s License/Driving Under the Influence (DUI) Checkpoint will be facilitated by the Oceanside Police Department at an undisclosed location in the City of Oceanside on Friday, December 12th, from 6 p.m. to 2 a.m. on Saturday, December 13th.

DUI checkpoint locations are determined based on data showing incidents of impaired-driving crashes. The primary purpose of DUI checkpoints is to promote public safety by removing drivers suspected of DUI from the roadway while also educating non-impaired motorists about the dangers of driving under the influence of alcohol and/or drugs. Officers will also ensure motorists passing through the checkpoint are properly licensed.

Although DUI incidents are commonly associated with alcohol, many prescription medications can also impair a driver. While a limited amount of cannabis (marijuana) is legal for adults 21 years and older to possess, it remains unlawful to drive while under the influence of cannabis. Motorists driving under the influence of any combination of drugs and/or alcohol are subject to arrest.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.

', '2025-12-29', '6pm-1am', 'https://www.oceansidepolice.com/Home/Components/News/News/841/12646', '2026-01-01 05:11:30.951716+00', null, '41015de9-20b1-434c-9544-952f3da178c6'), ('33', 'CA', 'Riverside', 'Indio', 'undisclosed location.', 'Department will conduct a driving under the influence (DUI) Checkpoint from 6:00 p.m. to 2:00 a.m. at an undisclosed location.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Sgt. Peter Fuentes said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The Indio Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license. 
Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-25', '6pm-2am', 'https://www.instagram.com/p/DSpx9_3kbiM/?img_index=1', '2026-01-01 05:14:41.991823+00', null, '040ae219-1237-4954-914c-3073fae4c7a2'), ('34', 'CA', 'Riverside', 'La Quinta', 'undisclosed location.', 'a Quinta, Calif. – On 01/09/2026, the Riverside County Sheriff’s Office will conduct a driving under the influence (DUI) Checkpoint from 8:00 PM until 2:00 AM. at an undisclosed location.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Deputy Lawrence Ponce said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The Riverside County Sheriff’s Office reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-09', '8am-2am', 'https://www.riversidesheriff.org/civicalerts.aspx?aid=6860', '2026-01-01 05:24:22.50652+00', null, 'd64743cd-153c-4fed-9eb7-5fcd4321efef'), ('35', 'CA', 'Riverside', 'Coachella', 'undisclosed location.', 'Coachella, Calif. – On 01/10/2026, the Riverside County Sheriff’s Office will conduct a driving under the influence (DUI) Checkpoint from 8:00 PM until 2:00 AM. at an undisclosed location.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Deputy Jason Beck said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The Riverside County Sheriff’s Office reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-10', '8am-2am', 'https://www.riversidesheriff.org/civicalerts.aspx?aid=6859', '2026-01-01 05:25:53.160177+00', null, '9442d4e5-1b36-4d28-a205-1f68a0c3de67'), ('36', 'CA', 'San Bernardino', 'Rialto', 'NA', 'Rialto, Calif. – On December 27, 2025, the Rialto Police Department will conduct a driving under the influence (DUI) checkpoint from 6 p.m., until 3 a.m., in a centralized area of the city where both commuter and pedestrian traffic are prevalent.                                                                                                                                                                                                               

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Rialto Police Chief Mark P. Kling said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The Rialto Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2025-12-27', '6pm-3am', 'https://rialtopolice.com/rialto-pd-holding-dui-checkpoint-dec-27/', '2026-01-01 05:27:23.216664+00', null, 'd789a3a6-bba8-4273-9632-fd925536445d'), ('37', 'CA', 'San Bernardino', 'San Bernardino  Area', 'undisclosed location.', 'San Bernardino, Calif. - Additional officers from the San Bernardino Police Department will be out on
patrol New Year’s Eve, December 31, 2025, from 6:00 p.m. to 2:00 a.m. looking for drivers suspected of
driving under the influence of alcohol and/or drugs.
“Impaired driving is preventable,” Traffic Sergeant Mike Siems said. “It’s a choice. If you’ve been drinking
or taken drugs that impair, make the right choice by finding a sober driver or alternate transportation to take
you places.”
San Bernardino Police Department reminds the public that impaired driving is not just from alcohol. Some
prescription medications and over-the-counter drugs may interfere with driving. Always follow directions
for use and read warning labels about driving. While medicinal and recreational marijuana are legal, driving
under the influence of marijuana is illegal.
Drivers caught driving impaired and charged with a first-time DUI face an average of $13,500 in fines and
penalties, as well as a suspended license.
Funding for this program is provided by a Grant from the California Office of Traffic Safety, through the
National Highway Traffic Safety Administration.', '2025-12-31', '6pm-2am', 'https://www.sanbernardino.gov/DocumentCenter/View/10987/SBPD---Press-Release---DUI-Patrols-123125?bidId=', '2026-01-01 05:28:39.046125+00', null, '53e83f7d-f231-4731-8047-ae52a0b4f205'), ('38', 'CA', 'Santa Clara', 'Milpitas', 'undisclosed location.', 'Over the weekend, we conducted a DUI & Driver’s License Checkpoint on E. Calaveras Blvd. near Town Center Dr. as part of our ongoing efforts to improve roadway safety. During the operation, 638 vehicles passed through the checkpoint and 304 drivers were screened, resulting in one DUI arrest and citations issued to several unlicensed and suspended drivers. 
DUI checkpoints are designed to promote safe driving and deter impaired driving, helping prevent crashes before they happen and was made possible by the hard work of our Traffic Safety Unit, patrol officers, professional staff, and funding  provided by a grant from the California Office of Traffic Safety.
We appreciate everyone who made responsible choices and helped keep our community safe. Thank you!!', '2025-12-27', '9pm-3am', 'https://www.facebook.com/MilpitasPD', '2026-01-01 05:30:58.929461+00', null, 'cc693710-60d7-4c78-83ae-1f5328061b36'), ('39', 'CA', 'Yolo', 'Woodland ', 'in central Woodland.  ', 'Woodland, Calif. – On 12/27/25, the Woodland Police Department will conduct a driving under the influence (DUI) Checkpoint from 7:00 PM – 2:00 AM in central Woodland. 

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes and impaired driving arrests. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.
The Woodland Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration. (RB)', '2025-12-27', '7pm-2am', 'https://www.instagram.com/p/DSoIMeyDIm7/', '2026-01-01 05:32:22.26239+00', null, '8d5195d8-d36d-4986-888f-087552a9c104'), ('40', 'CA', 'Los Angeles', 'Ponoma', 'Undisclosed location', 'Pomona Police Department will have additional officers on patrol on Friday, January 9, 2026, specifically looking for drivers suspected of being under the influence of alcohol and/or drugs. DUI patrols will be throughout the City of Pomona from 6:00 p.m. to 2:00 a.m.
 
In addition, Pomona Police Department will hold a DUI/Driver’s License Checkpoint on Friday, January 9, 2026, from 9:00 p.m. to 3:00 a.m. at an undisclosed location within the city limits of Pomona.
 
DUI checkpoints and patrols are done in locations with a history of DUI-related collisions and arrests. During the checkpoint, officers will be looking for signs of alcohol and/or drug impairment, with officers checking drivers for proper licensing.
 
In California, where approximately 30 percent of all traffic fatalities involve an impaired driver, checkpoints play an especially critical role in comprehensive traffic safety efforts. During 2024 and 2025, the Pomona Police Department recorded 405 DUI arrests and 211 crashes involving an impaired driver. There were a total of 31 fatalities and 74 injuries amongst those 211 crashes.
 
The Pomona Police Department reminds the public that impaired driving is not just from alcohol. Prescription or over-the-counter medications with an operating heavy machinery warning on the label can also impair. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.', '2026-01-09', '6pm-2am PST', 'https://www.pomonaca.gov/Home/Components/News/News/495/114?', '2026-01-20 06:02:41+00', null, '9c4e9119-93bc-414f-ad92-940c2c37a9fb'), ('41', 'CA', 'Los Angeles', 'Monterey Park ', 'Undisclosed location', null, '2026-01-09', '4pm-12am PST', 'https://www.montereypark.ca.gov/m/newsflash/home/detail/1275', '2026-01-20 06:06:15+00', null, 'd0dc5af1-c19e-402a-9579-0bcecfa20ef2'), ('42', 'CA', 'Alameda ', 'Oakland', 'undisclosed location', 'The Oakland Police Department will conduct a driving under the influence (DUI) Checkpoint on January 16, 2026, from 6:00 pm to 3:00 am at an undisclosed location.  
DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.
“Impaired drivers put others on the road at significant risk,” Lt. Tim Dolan said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”
The Oakland Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Office of Traffic Safety through the National Highway Traffic Safety Administration.', '2026-01-16', '6pm-3am PST', 'https://www.facebook.com/oaklandpoliceca/posts/pfbid02T81JmKC3mb4GVYbUu11GZ4FRE9G13bm1b8mQUS1pEQtcXGSY86g1B5tsHoUikGCZl?rdid=Cc11fXIBgBmjvPMz#', '2026-01-20 06:09:33+00', null, '47de4d96-ce85-46f3-9899-1431c084954b'), ('43', 'CA', 'San Francisco', 'San Francisco', 'undisclosed location', 'The San Francisco Police Department’s Traffic Unit will be conducting a DUI checkpoint patrol on Saturday, January 17th, 2026, between the hours of 7:00 P.M. and 3:00 A.M. The winter season can be dangerous for people on the road; the goal of the campaign is to stop suspected impaired drivers who put others at risk. Research shows that crashes involving an impaired driver can be reduced by up to 20 percent when well-publicized DUI checkpoints and proactive DUI patrols are conducted routinely.

Officers will be looking for signs of alcohol and/or drug impairment. When possible, specially trained officers will be available to evaluate those suspected of drug-impaired driving.  Recent statistics reveal that 30 percent of drivers in fatal crashes had one or more drugs in their systems.  A study of active drivers showed more tested positive for drugs that may impair driving (14 percent) than did for alcohol (7.3 percent). Of the drugs, marijuana was most prevalent, at 7.4 percent, slightly more than alcohol.

Drivers caught driving impaired can expect the impact of a DUI arrest to include jail time, fines, fees, DUI classes, and other expenses that can exceed $10,000, not to mention the embarrassment when friends and family find out.

SFPD encourages everyone to celebrate the winter season responsibly and make this a safe time for everyone on the road. Funding for this saturation is provided to the San Francisco Police Department by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration, reminding everyone to ‘Report Drunk Drivers – Call 9-1-1.', '2026-01-17', '7pm-3am PST', 'https://www.sanfranciscopolice.org/news/sfpd-conduct-dui-checkpoint-january-17-2026-26-002', '2026-01-20 06:13:13+00', null, '252d8103-0ce8-4fac-8e6e-a2b29c7d77b5'), ('44', 'CA', 'San Joaquin', 'Tracy', 'The hours and location of the checkpoint will not be released until 2 hours before it becomes operational.', 'The Tracy Police Department will conduct a sobriety and driver’s license safety checkpoint on Friday, January 16th.
Officers are targeting roads where there is a high frequency of intoxicated or unlicensed drivers. Traffic volume permitting, all vehicles will be checked for drivers who are under the influence of alcohol or drugs or driving unlicensed.
The hours and location of the checkpoint will not be released until 2 hours before it becomes operational. Signs will be posted on the roadway notifying drivers that the checkpoint is ahead, and information on the location of the checkpoint will be available on the Tracy Police Department''s Facebook and Instagram.', '2026-01-16', 'N/A', 'https://www.facebook.com/share/p/17oc5qy7aX/', '2026-01-20 06:19:03.970453+00', null, '89186d24-6bf0-411a-a3e2-4ab8b73e8c26'), ('45', 'CA', 'Fresno', 'Clovis', 'undisclosed location.', 'Clovis police will conduct a driving under the influence checkpoint Friday night from 8 p.m. to 1 a.m. at an undisclosed location, the department announced.

Checkpoint locations are selected based on data showing incidents of impaired driving-related crashes. Police said the primary goal is to promote public safety by removing suspected impaired drivers from the road.

“Impaired drivers put others on the road at significant risk,” said Corporal Mark Bradford, traffic supervisor. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

Police reminded the public that impairment is not limited to alcohol. Some prescription and over-the-counter medications can affect driving ability, and while medicinal and recreational marijuana are legal, driving under the influence of marijuana remains illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties and a suspended driver’s license, police said.

Funding for the checkpoint is provided by a grant from the California Highway Patrol’s Cannabis Tax Grant Program.', '2026-01-16', '8am-1am PST', 'https://gvwire.com/2026/01/16/clovis-police-to-hold-dui-checkpoint-friday-night/?', '2026-01-20 06:19:53+00', null, '714729dc-427d-4074-8361-f2f8bb6a8ebf'), ('46', 'CA', 'Orange', 'Santa Ana', 'undisclosed location', 'PUBLIC ADVISORY (January 15, 2026) On Saturday, January 17, 2026, the Santa Ana Police Department will conduct a driving under the influence (DUI) and driver’s license checkpoint.
The checkpoint will begin at 6:00 p.m. and conclude at 1:00 a.m. at an undisclosed location within the City of Santa Ana.
DUI checkpoint locations are determined based on data identifying areas with a history of impaired driving-related crashes. The primary purpose of a DUI checkpoint is to promote public safety by removing suspected impaired drivers from the roadway.
The Santa Ana Police Department reminds the public that impaired driving is not limited to alcohol consumption. Certain prescription medications and over-the-counter drugs may impair a person’s ability to drive safely. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, in addition to a suspended driver’s license. Funding for this operation is provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration ', '2026-01-17', '6pm-1am PST', 'https://www.facebook.com/share/p/1HZA5LXWHn/', '2026-01-20 06:21:43+00', null, 'c4675e1f-c40b-49f5-8b05-f2fcd44fb606'), ('47', 'CA', 'Orange', 'Garden Grove', 'undisclosed location', 'On January 30, 2026, the Garden Grove Police Department will conduct a driving under the influence (DUI) Checkpoint from 8:00 p.m. to 3:00 a.m. at an undisclosed location.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Garden Grove Police Chief Amir El-Farra said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The Garden Grove Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-30', '8pm-3am PST', 'https://ggcity.org/news/garden-grove-police-department-holding-dui-checkpoint-january-30', '2026-01-20 06:24:30+00', null, 'b04d61aa-cd29-47aa-b4dc-61c34eb806b8'), ('48', 'CA', 'Orange', 'Yorba Linda', 'undisclosed location', 'The Orange County Sheriff’s Department will be conducting a DUI/Driver’s License Checkpoint on Friday, January 2nd, from 6 p.m. to 2 a.m. at an undisclosed location in the city of Yorba Linda.

DUI Checkpoints are placed in locations based on collision statistics and frequency of DUI arrests. Deputies will be looking for signs of alcohol and/or drug impairment, with deputies checking drivers for proper licensing.

The Sheriff’s Department reminds drivers that “DUI Doesn’t Just Mean Booze.” If you take prescription drugs, particularly those with a driving or operating machinery warning on the label, you might be impaired enough to get a DUI. Marijuana can also be impairing, especially in combination with alcohol or other drugs, and can result in a DUI.', '2026-01-02', '6pm-2am PST', 'https://ocsheriff.gov/news/ocsd-hold-dui-checkpoint-yorba-linda-4', '2026-01-20 06:33:19+00', null, '828627c6-6649-46b5-9ae1-ba3a547a2fa0'), ('49', 'CA', 'San Benito', 'Ontario', 'undisclosed location', 'Ontario, CA – The Ontario Police Department will hold a DUI Checkpoint on January 16th from 6 p.m. to 2 a.m. at an undisclosed location within Ontario city limits.

Checkpoint locations are chosen based on a history of DUI crashes and arrests. The primary purpose of checkpoints is not to make arrests, but to promote public safety by deterring drivers from driving impaired.

During the checkpoint, officers will look for signs that drivers are under the influence of alcohol and/or drugs.

The Ontario Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications or over-the counter drugs may interfere with driving. Always follow directions for use and read warning labels about driving or ”operating heavy machinery,” which includes driving a car. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

If you plan on drinking or taking medications that may impact your ability to drive safely, plan on staying at home.

Drivers charged with DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-17', '6pm-2am PST', 'https://www.ontarioca.gov/news/ontario-police-department-holding-dui-checkpoint-january-16th?', '2026-01-20 06:36:54+00', null, '04cf70ea-44ab-4513-bfea-04f1c73a3117'), ('50', 'CA', 'San Bernardino', 'Colton', 'undisclosed location', 'On Friday, January 9th, 2026, the Colton Police Department will conduct a driving under the influence (DUI) & Driver’s License (CDL) Checkpoint from 7pm-3am, at an undisclosed location. 
The Colton Police Department reminds of public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana remains illegal. 
Driver charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license. 
Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-09', '7pm-3am PST', 'https://www.facebook.com/ColtonPD/posts/pfbid0H2xywS8vtQymXaoNBPNdRyf4PuL8YkGW9dD5CxxrX2s6tksbp6kSpUbrm8jps7dhl?rdid=a5XIZw2UKRrRpP1V#', '2026-01-20 06:39:02+00', null, 'e4ba303c-e846-4a15-8501-4e8aab2f27b4'), ('51', 'CA', 'San Bernardino', 'Redlands', 'undisclosed location', 'REDLANDS, Calif. — The Redlands Police Department will conduct a driving under the influence checkpoint beginning at 6 p.m. Friday, Jan. 9, and continuing until 1 a.m. Saturday at an undisclosed location.

Police said checkpoint locations are selected based on data showing areas with a history of impaired driving-related crashes. The goal of DUI checkpoints is to improve public safety by identifying and removing suspected impaired drivers from the road.

“Impaired drivers put others on the road at significant risk,” Traffic Bureau Sgt. Martin Gonzalez said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The department reminded drivers that impairment is not limited to alcohol. Prescription medications, over-the-counter drugs and marijuana can also impair driving ability. While recreational and medicinal marijuana are legal in California, driving under the influence of marijuana is illegal.

According to police, drivers arrested for a first-time DUI face an average of $13,500 in fines and penalties, along with a suspended driver’s license.

Funding for the checkpoint was provided by a grant from the California Office of Traffic Safety through the National Highway Traffic Safety Administration.', '2026-01-09', '6pm-1am PST', 'https://www.communityforwardredlands.com/redlands-police-to-hold-dui-checkpoint-friday-night/?', '2026-01-20 06:41:03+00', null, 'bbc7ae04-39f8-4126-8736-ca08f1a1f369'), ('52', 'CA', 'Shasta', 'Modesto', 'N/A', 'Modesto, Calif. – On January16, 2026 the Modesto Police Department will conduct a driving under the influence (DUI) Checkpoint from 8:00 pm to 3:00 am at an undisclosed location.  
DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.
“Impaired drivers put others on the road at significant risk,” Sergeant Darien Wilson said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improves traffic safety.”
Modesto Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.
Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.
Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-16', '8pm- 3am PST', 'https://www.facebook.com/modestopolice/posts/pfbid02rTZDFBNmz2eKFJzJMJLAaAwnzKY9QNZJRZjqgsZCKHZbNwBSGJQ8TnaAYVZXLQgcl?rdid=lNSjKFHj7XvE6s6V#', '2026-01-20 06:43:30+00', null, 'eab14d87-d990-4767-834f-c87b982da2d3'), ('53', 'CA', 'Santa Cruz', 'Redding', 'undisclosed location.', 'REDDING, Calif. — The Redding Police Department (RPD) will conduct a DUI checkpoint on Thursday, Jan. 8, from 5 p.m. to midnight at an undisclosed location within the city limits.

The checkpoint aims to enhance public safety by deterring impaired driving, rather than making arrests. Officers will be on the lookout for signs of alcohol and drug impairment.

RPD emphasizes that impairment can result from alcohol, prescription medications, or over-the-counter drugs. They advise drivers to heed medication warnings about operating vehicles. Although marijuana use is legal, driving under its influence is not.

The department urges those planning to consume alcohol or impairing medications to arrange for a designated driver or stay home. Convictions for driving under the influence can result in fines and penalties averaging $13,500 and a suspended license.

The checkpoint is funded by a grant from the California Highway Patrol Cannabis Tax Fund Grant Program. For more information on the matter, you can contact RPD Sergeant Brian Moore at (530)225-4264', '2026-01-08', '5pm- 12am PST', 'https://krcrtv.com/news/local/redding-police-to-conduct-dui-checkpoint-on-jan-8', '2026-01-13 06:45:33+00', null, '1a32620d-7629-4802-a15b-a4d07defc866'), ('54', 'CA', 'Stanislaus', null, 'undisclosed location.', 'The Stanislaus County Sheriff''s Office is conducting a DUI Checkpoint on Saturday January 3, 2026 within Stanislaus County. ', '2026-01-03', 'N/A', 'https://www.facebook.com/share/p/1Ffyj88L7r/', '2026-01-20 06:49:41.242872+00', null, 'a996194a-7146-40b6-beb5-d93325b6d7b1'), ('55', 'CA', 'Ventura', 'Thousand Oaks', 'undisclosed location.', null, '2026-01-09', '6pm-1am PST', 'https://www.facebook.com/VenturaCountySheriff/posts/pfbid0fbxVN97QeTXtckaVMKMNmxn7wzJDvd22onNnayMJ3vqHHV8XetSJLVCPypvgTp1Wl?rdid=KUHdykaMH7CdS9cf#', '2026-01-20 06:51:51+00', null, 'f8816835-ff84-4d36-aae4-b8cc0ceb8802'), ('56', 'CA', 'Yolo', 'Woodland ', 'in central Woodland.  ', 'DUI Checkpoint Saturday Night: December 27, 2025

Woodland, Calif. – On 12/27/25, the Woodland Police Department will conduct a driving under the influence (DUI) Checkpoint from 7:00 PM – 2:00 AM in central Woodland. 

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes and impaired driving arrests. The primary purpose of DUI checkpoints are to promote public safety by taking suspected impaired drivers off the road.
The Woodland Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration. (RB)', '2025-12-27', '7pm-2am PST', 'https://www.instagram.com/p/DSoIMeyDIm7/', '2026-01-20 06:52:58+00', null, '8d5195d8-d36d-4986-888f-087552a9c104'), ('57', 'CA', 'LA', 'Long Beach', 'East Division area', 'On Jan. 23, 2026, the Long Beach Police Department will conduct a driving under the influence (DUI)/Driver License (CDL) Checkpoint from 6:00 p.m. to 2:00 a.m. in the East Division area.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI/CDL checkpoints are to promote public safety by taking impaired drivers off the road, increase awareness of the dangers associated with drinking and driving, and serve a deterrent to potential impaired and unlicensed drivers.

“Impaired drivers put others on the road at significant risk,” Commander Jeremy Boshnack said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improve traffic safety.”

The Long Beach Police Department reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-23', '6pm-2am PST', 'https://www.longbeach.gov/police/press-releases/dui-checkpoint-on-jan.-23.-2026/', '2026-01-28 05:51:58+00', null, 'cd541bed-cbd0-4195-8f2c-d09b332363f4'), ('58', 'CA', 'Los Angeles', 'Ponoma', 'Undisclosed location', 'The Pomona Police Department will have additional officers on patrol on Friday, January 30, 2026, specifically looking for drivers suspected of being under the influence of alcohol and/or drugs. DUI patrols will be throughout the City of Pomona from 6:00 p.m. to 2:00 a.m.
 
In addition, there will be a DUI/Driver’s License Checkpoint on Friday, January 30, 2026, from 9:00 p.m. to 3:00 a.m. at an undisclosed location within the city limits of Pomona.
 
DUI checkpoints and patrols are done in locations with a history of DUI-related collisions and arrests. During the checkpoint, officers will be looking for signs of alcohol and/or drug impairment, with officers checking drivers for proper licensing.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration', '2026-01-10', '9pm-3am PST', 'https://www.pomonaca.gov/Home/Components/News/News/511/114?', '2026-01-28 05:54:04+00', null, '9c4e9119-93bc-414f-ad92-940c2c37a9fb'), ('59', 'CA', 'Orange', 'Irvine', 'undisclosed location', 'The Irvine Police Department will conduct a Driving Under the Influence (DUI) and Driver’s License checkpoint as part of the Department’s continued commitment to reducing injuries and deaths caused by impaired drivers. The checkpoint will take place on Saturday, January 31, from 7:00 p.m. to 2 a.m. Please drive sober, or get pulled over.  ', '2026-01-31', '7pm-2am PST', 'https://www.facebook.com/share/p/19amwRKyBm/', '2026-01-28 06:02:47+00', null, '607bf0d7-2e28-4c0e-9d03-e0c626c163e4'), ('60', 'CA', 'San Bernardino', 'Reiverside', 'Rancho California Road and Butterfield Stage Road', 'On January 23rd, 2026, the Riverside County Sheriff’s Office will conduct a driving under the influence (DUI) Checkpoint from 7:00 pm to 1:00 am at an undisclosed location in the city of Temecula.

DUI checkpoint locations are determined based on data showing incidents of impaired driving-related crashes. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road.

“Impaired drivers put others on the road at significant risk,” Deputy Lopez said. “Any prevention measures that reduce the number of impaired drivers on our roads significantly improves traffic safety.”

The Riverside County Sheriff’s Office reminds the public that impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs may interfere with driving. While medicinal and recreational marijuana are legal, driving under the influence of marijuana is illegal.

Drivers charged with a first-time DUI face an average of $13,500 in fines and penalties, as well as a suspended license.

Funding for this program was provided by a grant from the California Office of Traffic Safety, through the National Highway Traffic Safety Administration.', '2026-01-23', '7pm-1am PST', 'https://www.riversidesheriff.org/m/newsflash/home/detail/6894', '2026-01-28 06:04:17+00', null, '2948bf73-854f-4dc6-ad70-1b56f193e24c'), ('61', 'CA', 'San Mateo', 'San Mateo', 'Barneson and Alameda de las Pulgas', 'Our next DUI Checkpoint will be this Friday, January 30th. Officers will be in the area of Barneson and Alameda de las Pulgas from approximately 6pm-2am. ', '2026-01-31', '6pm-2am PST', 'https://www.facebook.com/share/p/17mkeUhaK7/', '2026-01-28 06:09:39+00', null, 'e1e37e1a-75d7-4dae-b88d-5587b3fe4ebf'), ('62', 'CA', 'Santa Clara', 'gilroy', 'N/A', 'On Friday, January 30, 2026, the Gilroy Police Department will be conducting a DUI checkpoint from 6 pm to 1 am at an undisclosed location within the City of Gilroy.

DUI checkpoint locations are determined based on data showing incidents where crashes are directly related to whether a driver is impaired. The primary purpose of DUI checkpoints is to promote public safety by taking suspected impaired drivers off the road. And, drivers charged with a first-time DUI offense face an average of $13,500 in fines and penalties, as well as a suspended license.

“Impaired drivers put others on the road at significant risk,” Sgt. Raul Razo said. “Any prevention measures that can reduce the number of impaired drivers on our roads significantly improves traffic safety.”

As a reminder -- impaired driving is not just from alcohol. Some prescription medications and over-the-counter drugs, along with medicinal and recreational cannabis, can interfere with driving. Also as a reminder, driving under the influence of cannabis is illegal.', '2026-01-28', '6pm-1am PST', 'https://www.instagram.com/p/DT3iTPxk3vK/', '2026-01-28 06:14:44+00', null, 'c998b310-cd1b-4ba3-83af-d0a1eb1b157d');